name: gpu
channels:
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.1.0
  - abseil-cpp=20210324.2
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - astor=0.8.1
  - asttokens=3.0.0
  - astunparse=1.6.3
  - async-timeout=5.0.1
  - attrs=24.3.0
  - blas=1.0
  - brotlicffi=1.0.9.2
  - ca-certificates=2025.7.14
  - certifi=2025.7.14
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=8.1.8
  - colorama=0.4.6
  - comm=0.2.3
  - cpython=3.9.23
  - cryptography=41.0.3
  - cudatoolkit=11.3.1
  - cudnn=8.2.1
  - debugpy=1.8.15
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - frozenlist=1.5.0
  - gast=0.4.0
  - giflib=5.2.2
  - google-auth-oauthlib=0.4.1
  - google-pasta=0.2.0
  - grpcio=1.42.0
  - h5py=3.14.0
  - hdf5=1.14.5
  - icc_rt=2022.1.0
  - icu=68.1
  - idna=3.7
  - importlib-metadata=8.5.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.18.1
  - jedi=0.19.2
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - keras-preprocessing=1.1.2
  - krb5=1.21.3
  - libcurl=8.14.1
  - libpng=1.6.39
  - libprotobuf=3.17.2
  - libsodium=1.0.20
  - libssh2=1.10.0
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown=3.8
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpi=1.0
  - mpi4py=4.0.3
  - msmpi=10.1.1
  - msys2-conda-epoch=20160418
  - multidict=6.1.0
  - nest-asyncio=1.6.0
  - oauthlib=3.3.1
  - openssl=1.1.1w
  - opt_einsum=3.3.0
  - packaging=25.0
  - parso=0.8.4
  - pickleshare=0.7.5
  - pip=25.1
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - propcache=0.3.1
  - protobuf=3.17.2
  - psutil=7.0.0
  - pure_eval=0.2.3
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.2
  - pybind11-abi=5
  - pycparser=2.21
  - pygments=2.19.2
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.9.0
  - python-dateutil=2.9.0.post0
  - python_abi=3.9
  - pywin32=311
  - pyzmq=27.0.0
  - requests=2.32.4
  - requests-oauthlib=2.0.0
  - rsa=4.7.2
  - scipy=1.13.1
  - setuptools=78.1.1
  - six=1.17.0
  - snappy=1.2.1
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tbb=2021.8.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow-gpu=2.6.0
  - termcolor=2.1.0
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - ucrt=10.0.22621.0
  - urllib3=2.5.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.13
  - werkzeug=3.1.3
  - wheel=0.35.1
  - win_inet_pton=1.1.0
  - wrapt=1.17.0
  - xz=5.6.4
  - yarl=1.18.0
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.3.1
      - affine==2.4.0
      - cachetools==4.2.4
      - clang==5.0
      - click-plugins==1.1.1.2
      - cligj==0.7.2
      - flatbuffers==25.2.10
      - google-auth==1.34.0
      - joblib==1.5.1
      - keras==2.10.0
      - libclang==18.1.1
      - numpy==1.24.0
      - pandas==2.3.1
      - pyparsing==3.2.3
      - pytz==2025.2
      - rasterio==1.4.3
      - scikit-learn==1.6.1
      - tensorboard==2.10.1
      - tensorflow==2.10.0
      - tensorflow-estimator==2.10.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - threadpoolctl==3.6.0
      - tzdata==2025.2
prefix:
